<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="BPELProcess"
     targetNamespace="http://xmlns.oracle.com/ATeamDynamic/DynamicDriver2/BPELProcess"
     xmlns:ns2="http://schemas.xmlsoap.org/ws/2003/03/addressing"
     xmlns:ns1="http://www.oracle.com/ateam/dynamic"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:ns3="http://docs.oasis-open.org/wsbpel/2.0/serviceref"
     xmlns:client="http://xmlns.oracle.com/ATeamDynamic/DynamicDriver2/BPELProcess"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="BPELProcess">
        <plnk:role name="BPELProcessProvider" portType="client:BPELProcess"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.oracle.com/ateam/dynamic" schemaLocation="xsd/common.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://schemas.xmlsoap.org/ws/2003/03/addressing" schemaLocation="xsd/ws_addressing.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://docs.oasis-open.org/wsbpel/2.0/serviceref" schemaLocation="xsd/ws-bpel_serviceref.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="BPELProcessRequestMessage">
        <wsdl:part name="payload" element="ns1:input"/>
    </wsdl:message>
    <wsdl:message name="BPELProcessResponseMessage">
        <wsdl:part name="payload" element="ns1:output"/>
    </wsdl:message>
    <wsdl:portType name="BPELProcess">
        <wsdl:operation name="process">
            <wsdl:input message="client:BPELProcessRequestMessage"/>
            <wsdl:output message="client:BPELProcessResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
